USE [SMART_M_LISBON]
GO

/****** Object:  View [dbo].[VDIM_PUBLIC_TRANSP_SHAPES]  Script Date: 25/03/2020 15:31:02 ******/
DROP VIEW [dbo].[VDIM_PUBLIC_TRANSP_SHAPES]
GO

/****** Object:  View [dbo].[VDIM_PUBLIC_TRANSP_SHAPES]   Script Date: 25/03/2020 15:31:02 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO





CREATE VIEW [dbo].[VDIM_PUBLIC_TRANSP_SHAPES] AS

SELECT DISTINCT
       [SHAPE_ID]
	  ,'MT_' + [SHAPE_ID] AS SHAPE_CODE
      ,[LINE_NAME] AS LINE_FULL_NAME
	  ,SUBSTRING( [LINE_NAME] ,1, CHARINDEX(' - ',[LINE_NAME])-1)  AS LINE_NAME
	  ,SUBSTRING( [LINE_NAME] , CHARINDEX(' - ',[LINE_NAME])+3,LEN([LINE_NAME]))  AS LINE_DIRECTION
  FROM [SMART_M_LISBON].[dbo].[METRO_SHAPES_GROUP]

  UNION

  SELECT DISTINCT
       [SHAPE_ID]
	  ,'CR_' + [SHAPE_ID]  AS SHAPE_CODE
      ,[LINE_NAME] AS LINE_FULL_NAME
	  ,SUBSTRING( [LINE_NAME] ,1, CHARINDEX(' - ',[LINE_NAME])-1)  AS LINE_NAME
	  ,SUBSTRING( [LINE_NAME] , CHARINDEX(' - ',[LINE_NAME])+3,LEN([LINE_NAME]))  AS LINE_DIRECTION
  FROM [SMART_M_LISBON].[dbo].[CARRIS_SHAPES_GROUP]




GO


