USE [SMART_M_LISBON]
GO

/****** Object:  View [dbo].[VDIM_PUB_TRANSP]  Script Date: 08/03/2020 21:42:21 ******/
DROP VIEW [dbo].[VDIM_PUB_TRANSP]
GO

/****** Object:  View [dbo].[VDIM_PUB_TRANSP]   Script Date: 08/03/2020 21:42:21 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VDIM_PUB_TRANSP] AS

SELECT 
	   [ID_CARRIS_SHAPES_GROUP]
      ,[STOP_ID]
      ,[STOP_NAME]
      ,[STOP_SEQ]
      ,'CR_' + [SHAPE_ID] AS 
      ,[LINE_NAME]
      ,[SHAPE_SEQ_1]
      ,[SHAPE_SEQ_2]
	  ,SUBSTRING( [LINE_NAME] ,1, CHARINDEX(' - ',[LINE_NAME])-1)   AS LINE_CODE
	  ,SUBSTRING( [LINE_NAME] , CHARINDEX(' - ',[LINE_NAME])+3,LEN([LINE_NAME])) AS LINE_CODE_NAME
  FROM [SMART_M_LISBON].[dbo].[CARRIS_SHAPES_GROUP] A

 UNION 

 SELECT [ID_METRO_SHAPES_GROUP]
      ,[STOP_ID]
      ,[STOP_NAME]
      ,[STOP_SEQ]
      ,'MT_' + [SHAPE_ID]
      ,[LINE_NAME]
      ,[SHAPE_SEQ_1]
      ,[SHAPE_SEQ_2]
	  ,SUBSTRING( [LINE_NAME] ,1, CHARINDEX(' - ',[LINE_NAME])-1)  AS LINE_CODE
	  ,SUBSTRING( [LINE_NAME] , CHARINDEX(' - ',[LINE_NAME])+3,LEN([LINE_NAME]))  AS LINE_CODE_NAME
  FROM [SMART_M_LISBON].[dbo].[METRO_SHAPES_GROUP] B



GO


