USE [SMART_M_LISBON]
GO

/****** Object:  View [dbo].VDIM_PREDICT_CARRIS    Script Date: 25/08/2020 18:11:58 ******/
DROP VIEW [dbo].VDIM_PREDICT_CARRIS
GO

/****** Object:  View [dbo].VDIM_PREDICT_CARRIS    Script Date: 25/08/2020 18:11:58 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




CREATE VIEW [dbo].VDIM_PREDICT_CARRIS AS

SELECT distinct
       [LS_DISPLAY_CODE]
      ,[DISPLAY_LAT]
      ,[DISPLAY_LONG]
	  ,[STOP_NAME]
  FROM [SMART_M_LISBON].[dbo].[VFACT_EVENTS_PUBLIC_TRANSPORTS_STOPS] VFPTS
    INNER JOIN VFACT_PREDICT_CARRIS VFPC ON VFPC.[Stop Id] = VFPTS.[LS_DISPLAY_CODE]
	INNER JOIN VDIM_PUBLIC_TRANSP_STOPS VDPS ON VDPS.[STOP_CODE] = VFPTS.[LS_DISPLAY_CODE]
    Where [LS_DISPLAY_CODE] not like '%EV%'



GO


