USE [SMART_M_LISBON]
GO

/****** Object:  View [dbo].[VDIM_WAZE_TRAFFIC]    Script Date: 20/03/2020 12:59:34 ******/
DROP VIEW [dbo].[VDIM_WAZE_TRAFFIC]
GO

/****** Object:  View [dbo].[VDIM_WAZE_TRAFFIC]    Script Date: 20/03/2020 12:59:34 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VDIM_WAZE_TRAFFIC] AS

SELECT [ID_WASE]
	  ,'TW_' + CAST([ID_WASE] AS VARCHAR(30)) AS [WASE_CODE]
      ,[LOCALIDADE] AS LOCALITY
      ,[DELAY]
      ,[ENDNODE] AS END_NODE_STREET_NAME
      ,[SOURCE_ID_ENITY] AS SOURCE_ENTETY
      ,[ROAD_LENGTH]
      ,[TRAFFIC_LEVEL]
      ,[ROAD_TYPE]
      ,[SPEED]
      ,[STREET] AS STREET_NAME
      ,[VALIDITY_TS] AS WAZE_END_DATETIME
      ,[TRAFFIC_DATE] AS WAZE_DATE
  FROM [SMART_M_LISBON].[dbo].[WASE_TRAFFIC_CONTROL]


GO


