USE [SMART_M_LISBON]
GO

/****** Object:  View [dbo].[VDIM_PUBLIC_TRANSP_STOPS]    Script Date: 25/03/2020 15:30:59 ******/
DROP VIEW [dbo].[VDIM_PUBLIC_TRANSP_STOPS]
GO

/****** Object:  View [dbo].[VDIM_PUBLIC_TRANSP_STOPS]    Script Date: 25/03/2020 15:30:59 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




CREATE VIEW [dbo].[VDIM_PUBLIC_TRANSP_STOPS] AS

SELECT DISTINCT
	   [STOP_ID]
	  ,'CR_' + [STOP_ID] AS STOP_CODE
      ,[STOP_NAME]
      --,SUBSTRING([LINE_NAME],1,3) AS LINE_NAME
	 -- ,SUBSTRING([LINE_NAME],7,LEN([LINE_NAME])) AS LINE_DIRECTION
	  --,[LINE_NAME] AS [LINE_FULL_NAME]
  FROM [SMART_M_LISBON].[dbo].[CARRIS_STOPS_GROUP]

  UNION

  SELECT DISTINCT
	   [STOP_ID]
	  ,'MT_' + [STOP_ID] AS STOP_CODE
      ,[STOP_NAME]
	 -- ,SUBSTRING( [LINE_NAME] ,1, CHARINDEX(' - ',[LINE_NAME])-1)  AS LINE_NAME
	  --,SUBSTRING( [LINE_NAME] , CHARINDEX(' - ',[LINE_NAME])+3,LEN([LINE_NAME]))  AS LINE_DIRECTION
	  --,[LINE_NAME] AS [LINE_FULL_NAME]
  FROM [SMART_M_LISBON].[dbo].[METRO_STOPS_GROUP]




GO


