USE [SMART_M_LISBON]
GO

/****** Object:  View [dbo].[VFACT_EVENTS_CROWD]    Script Date: 05/03/2020 21:05:24 ******/
DROP VIEW [dbo].[VFACT_EVENTS_CROWD]
GO

/****** Object:  View [dbo].[VFACT_EVENTS_CROWD]    Script Date: 05/03/2020 21:05:24 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Script for SelectTopNRows command from SSMS  ******/
CREATE VIEW [dbo].[VFACT_EVENTS_CROWD] AS
SELECT
 [KEY_EVENT_CROWD]
,[LS_EVENT_CODE]
,[ID_EVENT]
,[EVENT_DATE]
,[LS_DISPLAY_CODE]
,[DISPLAY_LAT]
,[DISPLAY_LONG]
,[DISPLAY_DATE]
,[DISPLAY_TIME]
,[EVENT_CROWD_DISTANCE]
,[FLAG_NEAR_EV_vs_AC]
,[CONCENTRATION] AS [POPULATION]
,[AVERAGE_COVERAGE] AS [COVERAGE]
  FROM [SMART_M_LISBON].[dbo].[FACT_EVENTS_CROWD]

GO


