USE [SMART_M_LISBON]
GO

/****** Object:  Table [dbo].[FACT_EVENTS_PUB_TRANSP_STOPS]    Script Date: 05/05/2020 11:38:21 ******/
DROP TABLE [dbo].[FACT_EVENTS_PUB_TRANSP_STOPS]
GO

/****** Object:  Table [dbo].[FACT_EVENTS_PUB_TRANSP_STOPS]    Script Date: 05/05/2020 11:38:21 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FACT_EVENTS_PUB_TRANSP_STOPS](
	[KEY_EVENT_STOP] [int] IDENTITY(1,1) NOT NULL,
	[LS_EVENT_CODE] [varchar](28) NULL,
	[ID_EVENT] [int] NULL,
	[EVENT_DATE] [date] NULL,
	[LS_DISPLAY_CODE] [varchar](28) NULL,
	[DISPLAY_LAT] [float] NULL,
	[DISPLAY_LONG] [float] NULL,
	[DISPLAY_DATE] [date] NULL,
	[EVENT_PUBTRANSP_DISTANCE] [float] NULL,
	[M_FLAG_NEAR_EV] [int] NULL,
	[ID_POSITION_EVENT] [int] NULL
) ON [PRIMARY]

GO


