USE [SMART_M_LISBON]
GO

/****** Object:  Table [dbo].[FACT_EVENTS_PUB_TRANSP_SHAPES]    Script Date: 05/05/2020 11:38:49 ******/
DROP TABLE [dbo].[FACT_EVENTS_PUB_TRANSP_SHAPES]
GO

/****** Object:  Table [dbo].[FACT_EVENTS_PUB_TRANSP_SHAPES]    Script Date: 05/05/2020 11:38:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FACT_EVENTS_PUB_TRANSP_SHAPES](
	[KEY_EVENT_STOP] [int] IDENTITY(1,1) NOT NULL,
	[LS_EVENT_CODE] [varchar](28) NULL,
	[ID_EVENT] [int] NULL,
	[EVENT_DATE] [date] NULL,
	[LS_STOP_CODE] [varchar](28) NULL,
	[STOP_LAT] [float] NULL,
	[STOP_LONG] [float] NULL,
	[DISPLAY_DATE] [date] NULL,
	[DISPLAY_SHAPE_CODE] [varchar](28) NULL,
	[DISPLAY_SHAPE_LAT_1] [float] NULL,
	[DISPLAY_SHAPE_LONG_1] [float] NULL,
	[DISPLAY_SHAPE_LAT_2] [float] NULL,
	[DISPLAY_SHAPE_LONG_2] [float] NULL,
	[EVENT_PUBTRANSP_DISTANCE] [float] NULL,
	[M_FLAG_NEAR_EV] [int] NULL,
	[LINE_FLAG_NEAR_EVENT] [int] NULL,
	[ID_POSITION_EVENT] [int] NULL
) ON [PRIMARY]

GO


