USE [SMART_M_LISBON]
GO

/****** Object:  Table [dbo].[FACT_EVENT_CARRIS_DISTANCE]    Script Date: 01/03/2020 23:04:01 ******/
DROP TABLE [dbo].[FACT_EVENT_CARRIS_DISTANCE]
GO

/****** Object:  Table [dbo].[FACT_EVENT_CARRIS_DISTANCE]    Script Date: 01/03/2020 23:04:01 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FACT_EVENT_CARRIS_DISTANCE](
	[ID_DISTANCE] [int] IDENTITY(1,1) NOT NULL,
	[LS_EVENT_CODE] [varchar](8) NULL,
	[LS_INTERNAL_EVENT_ID] [int] NULL,
	[LS_CARRIS_CODE] [varchar](28) NULL,
	[LS_INTERNAL_CARRIS_ID] [int] NULL,
	[DIST_EVENT_VS_CARRIS] [real] NULL
) ON [PRIMARY]

GO


